/*
*Generated by GeniusPlatform. 2016-04-11 15:57:15
*/
package com.genius.BOSS.cont_verify.action;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.jdom.Document;
import org.jdom.Element;
import org.jdom.output.Format;
import org.jdom.output.XMLOutputter;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.Controller;

import com.genius.BOSS.cont_verify.ICont_verify;
import com.genius.BOSS.cont_verify.actionbean.*;

public final class InsertSelectEditAction implements Controller {
	public ModelAndView handleRequest(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
		HttpSession session = request.getSession();
		
		if (session.getAttribute("login") == null
				|| (!session.getAttribute("login").equals("true"))) {
			Element root = new Element("entity");
			
			Element actionState = new Element("actionState");
			Element fieldState = new Element("field");
			fieldState.setAttribute("name", "state");
			fieldState.setAttribute("value", "noSession");
			actionState.addContent(fieldState);

			root.addContent(actionState);
			Document doc = new Document(root);
			response.setContentType("application/xml;charset=GB2312");
			Format format = Format.getPrettyFormat();
			format.setEncoding("GB2312");
			XMLOutputter outer = new XMLOutputter(format);
			outer.output(doc, response.getWriter());

			return null;
		}
		
				String id = request.getParameter("id");

		
		ApplicationContext context = new ClassPathXmlApplicationContext(
				"applicationContext.xml");

		ICont_verify cont_verify = (ICont_verify) context
				.getBean("cont_verifyProxy");
		cont_verify.setSId(session.getAttribute("userId").toString());
		
		InsertActionBean bean = new InsertActionBean();
		bean = cont_verify.insertSelectEdit(id);
		
		Element root = new Element("entity");
		Element row = new Element("row");
		
		
		Element field0 = new Element("field");
		field0.setAttribute("name", "id");
		field0.setAttribute("value", id);
		row.addContent(field0);
		
		Element field1 = new Element("field");
		field1.setAttribute("name", "account");
		field1.setAttribute("value", bean.getAccount()==null?"":bean.getAccount());
		row.addContent(field1);
		
		Element field2 = new Element("field");
		field2.setAttribute("name", "name");
		field2.setAttribute("value", bean.getName()==null?"":bean.getName());
		row.addContent(field2);
		
		Element field3 = new Element("field");
		field3.setAttribute("name", "email");
		field3.setAttribute("value", bean.getEmail()==null?"":bean.getEmail());
		row.addContent(field3);
		
		Element field4 = new Element("field");
		field4.setAttribute("name", "phone_no");
		field4.setAttribute("value", bean.getPhone_no()==null?"":bean.getPhone_no());
		row.addContent(field4);
		
		Element field5 = new Element("field");
		field5.setAttribute("name", "head_img");
		field5.setAttribute("value", bean.getHead_img()==null?"":bean.getHead_img());
		row.addContent(field5);
		
		Element field6 = new Element("field");
		field6.setAttribute("name", "sex");
		field6.setAttribute("value", bean.getSex()==null?"":bean.getSex());
		row.addContent(field6);
		
		Element field7 = new Element("field");
		field7.setAttribute("name", "idcard_img");
		field7.setAttribute("value", bean.getIdcard_img()==null?"":bean.getIdcard_img());
		row.addContent(field7);
		
		Element field8 = new Element("field");
		field8.setAttribute("name", "id_card_no");
		field8.setAttribute("value", bean.getId_card_no()==null?"":bean.getId_card_no());
		row.addContent(field8);
		
		Element field9 = new Element("field");
		field9.setAttribute("name", "birthday");
		field9.setAttribute("value", bean.getBirthday()==null?"":bean.getBirthday());
		row.addContent(field9);
		
		Element field10 = new Element("field");
		field10.setAttribute("name", "role");
		field10.setAttribute("value", bean.getRole()==null?"":bean.getRole());
		row.addContent(field10);
		
		Element field11 = new Element("field");
		field11.setAttribute("name", "register_time");
		field11.setAttribute("value", bean.getRegister_time()==null?"":bean.getRegister_time());
		row.addContent(field11);
		
		Element field12 = new Element("field");
		field12.setAttribute("name", "is_identify");
		field12.setAttribute("value", bean.getIs_identify()==null?"":bean.getIs_identify());
		row.addContent(field12);
		
		Element field13 = new Element("field");
		field13.setAttribute("name", "status");
		field13.setAttribute("value", bean.getStatus()==null?"":bean.getStatus());
		row.addContent(field13);
		
		Element field14 = new Element("field");
		field14.setAttribute("name", "point");
		field14.setAttribute("value", bean.getPoint()==null?"":bean.getPoint());
		row.addContent(field14);
		
		Element field15 = new Element("field");
		field15.setAttribute("name", "credit");
		field15.setAttribute("value", bean.getCredit()==null?"":bean.getCredit());
		row.addContent(field15);
		
		Element field16 = new Element("field");
		field16.setAttribute("name", "cert_img");
		field16.setAttribute("value", bean.getCert_img()==null?"":bean.getCert_img());
		row.addContent(field16);
		
		Element field17 = new Element("field");
		field17.setAttribute("name", "area");
		field17.setAttribute("value", bean.getArea()==null?"":bean.getArea());
		row.addContent(field17);
		
		root.addContent(row);
		
		Element actionState = new Element("actionState");
		Element fieldState = new Element("field");
		fieldState.setAttribute("name", "state");
		fieldState.setAttribute("value", "session");
		actionState.addContent(fieldState);
		root.addContent(actionState);

		Document doc = new Document(root);
		response.setContentType("application/xml;charset=GB2312");
		Format format = Format.getPrettyFormat();
		format.setEncoding("GB2312");
		XMLOutputter outer = new XMLOutputter(format);
		outer.output(doc, response.getWriter());

		return null;
		
	}
}
