/*
*Generated by LiuRunze. 2016-04-09 15:08:41
*/
package com.genius.BOSS.login.action;

import java.io.IOException;

import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.log4j.Logger;
import org.genius.log.LogDatabaseAdvice;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.Controller;
import com.genius.adminmanager.useronline.action.HttpSessionBinding;
import com.genius.adminmanager.LoginJsp;
import com.genius.adminmanager.userinfo.Userinfo;
import com.genius.adminmanager.userinfo.UserinfoBean;
import com.genius.search.search.Suserinfo;
import com.genius.BOSS.login.Login;


public final class LoginAction implements Controller {
	public ModelAndView handleRequest(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
			
		HttpSession session = request.getSession();
		ServletContext application = session.getServletContext();
		
		String username = request.getParameter("username");
		String password = request.getParameter("password");
		String rand = request.getParameter("rand");
		boolean loginFlag = false;
		String randCode = session.getAttribute("rand").toString();
		
		if(username == null && password == null && randCode.equals("")) {
			username = session.getAttribute("name").toString();
			password = "";
			loginFlag = true;
		}
		
		if(username == null && password == null && !randCode.equals("")) {
			return new ModelAndView("/login.jsp");
		}

		Login login = new Login();
		if (!loginFlag && !rand.equals(randCode) && randCode!="") {
			Logger logger = Logger.getLogger(LoginAction.class);
			logger.fatal(username + " Login Failure!");
			request.setAttribute("info","#001");
			return new ModelAndView("/login.jsp");
		}
		
		boolean result = true;
		String[] lawlessWord = {"select","insert","update","delete","create","char(","exec","asc(","ascii(","unicode",};
		for(String word:lawlessWord)
			if(username.toLowerCase().indexOf(word)!=-1)
				result = false;
		if(result==false){
			Logger logger = Logger.getLogger(LoginAction.class);
			logger.fatal(username + " Login Failure!");
			request.setAttribute("info","#002");
			return new ModelAndView("/login.jsp");
		}	
		String[] lawless = {"'",";","(",")",",","=","\""};
		for(String str:lawless)
			username = username.replace(str,"");	
		
		try {
			if (login.check(username, password)) {	
				session.setAttribute("userName", username);
				session.setAttribute("userIp", request.getRemoteAddr());
				session.setAttribute("login", "true");
				session.setAttribute("rand", "");
				Userinfo userInfo = new Userinfo();
				UserinfoBean bean = userInfo.getUserinfo(username);
				session.setAttribute("userId", bean.getId());
				//******search********
				session.setAttribute("departmentId",bean.getDepartmentId());
				Suserinfo suserinfo=new Suserinfo();
				if (suserinfo.roleChek(bean.getRoleId())){
					session.setAttribute("power",bean.getRoleId());
				} else	session.setAttribute("power","9999");
				//******search*********
				session.setAttribute("roleId", bean.getRoleId());
				session.setAttribute("name", bean.getName() == null ? "" : bean
						.getName());
				session.setAttribute("style",
						bean.getStyle() == null ? "default/fresh" : bean
								.getStyle());
				Logger logger = Logger.getLogger(LoginAction.class);
				logger.fatal(session.getAttribute("userName") + " Login Success!");
				login.log(session.getAttribute("userId").toString(),
						LogDatabaseAdvice.TYPE_LOGIN);
				session.setAttribute("BindingNotify",new HttpSessionBinding(application));
				return new ModelAndView("/main.jsp");
			} else {
				Logger logger = Logger.getLogger(LoginAction.class);
				logger.fatal(username + " Login Failure!");
				request.setAttribute("info","#002");
				return new ModelAndView("/login.jsp");
			}
		} catch (Exception e) {
			request.setAttribute("info","#004");
			return new ModelAndView("/login.jsp");
		}
	}
}

