/*
*Generated by LiuRunze. 2009-06-09 18:02:15
*/
package com.genius.search.tablelist;

import java.util.ArrayList;

import org.genius.power.IPower;

import com.genius.search.tablelist.actionbean.*;;

public interface ITablelist extends IPower {
	
	public int getTotalSize();

	public void setTotalSize(int totalSize);

	public String getSelectSql();

	public void setSelectSql(String selectSql);

	public ArrayList select(int pageNo, String orderField, String orderType, String searchField,String searchValue,String filter);
	
	
	
	
	
	
	
	public InsertActionBean insertSelectEdit(String id);
	
	public boolean insertNew(String tablevalue,String tabletext,String bz);
	
	public boolean insertEdit(String tablevalue,String tabletext,String bz,String id);
	
	
	
	
	
	
	
	
	
	
	
	
	
	public boolean delete(String[] id);
	
	
	
	

}
