/*
*Generated by LiuRunze. 2009-06-09 18:02:15
*/
package com.genius.search.tablelist;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

import org.genius.data.DataConfig;
import org.genius.data.PageDataConfig;
import org.genius.power.Permission;

import com.genius.search.tablelist.actionbean.InsertActionBean;
import com.genius.search.tablelist.actionbean.SelectActionBean;

public class Tablelist implements ITablelist {

	public int totalSize;

	public String selectSql;
	
	private String selectSumSql;
	
	private String sId;
	
	public int getTotalSize() {
		return totalSize;
	}

	public void setTotalSize(int totalSize) {
		this.totalSize = totalSize;
	}

	public String getSelectSql() {
		return selectSql;
	}

	public void setSelectSql(String selectSql) {
		this.selectSql = selectSql;
	}
	
	public String getSId() {
		return sId;
	}

	public void setSId(String sId) {
		this.sId=sId;
		
	}
	
	
	public ArrayList select(int pageNo, String orderField, String orderType, String searchField,String searchValue, String filter){
		boolean asc;
		PageDataConfig myData = new PageDataConfig(20, pageNo);
		myData.init(20, pageNo);
		ArrayList<SelectActionBean> myList=new ArrayList<SelectActionBean>();
		try {
			myData.openConnection();
			String sql ="select id,tablevalue,tabletext,bz from s_q_tablelist";

			if (filter != null) {
				Permission permission = new Permission();
				sql = permission.filterSql(sql, filter);
			}
			
			if (searchField!=null && searchField.equals("ADSsearchADS")) {
				sql = "select * from(" + sql + ") my_table where " + searchValue ;
			}else if (searchField != null && searchValue != null && !searchField.equals("null") && !searchValue.equals("null")) {
				sql = "select * from(" + sql + ") my_table where " + searchField+ " like '%" + searchValue + "%'";
			
			}

			if(orderField==null||orderField.equals("null")){
				orderField="id";
			}
			if(orderType==null||orderType.equals("null")){
				asc=false;
			}else if(orderType.equals("true")){
				asc=true;
			}else if(orderType.equals("false")){
				asc=false;
			}else{
				asc=false;
			}

			this.selectSumSql=sql;
			if (asc == true) {
				this.selectSql = "select * from(" + sql
						+ ") my_table_order order by  " + orderField + " asc";
			} else {
				this.selectSql = "select * from(" + sql
						+ ") my_table_order order by  " + orderField + " desc";
			}

			ResultSet rs=myData.executeQueryForSqlServer(sql, "id",orderField, asc );
			
			while(rs.next()){
				SelectActionBean tablelistBean=new SelectActionBean();
				tablelistBean.setId(rs.getString("id"));
				tablelistBean.setTablevalue(rs.getString("tablevalue"));
				tablelistBean.setTabletext(rs.getString("tabletext"));
				tablelistBean.setBz(rs.getString("bz"));
				myList.add(tablelistBean);
				tablelistBean=null;
			}
			totalSize = myData.getTotalSize();
			rs.close();
		} catch (SQLException e) {
			e.printStackTrace();
		 }finally{
			myData.closeConnection();
		}
		return myList;
	}
	
	public boolean insertNew(String tablevalue,String tabletext,String bz){

		boolean result = false;
		DataConfig myData = new DataConfig();
		try {
			myData.openConnection();
			String sql1 ="insert into s_q_tablelist (tabletext,tablevalue,bz) values ('" + tabletext + "','" + tablevalue + "','" + bz + "')";
			myData.executeUpdate(sql1);
			result = true;
		} catch (SQLException e) {
			e.printStackTrace();
		} finally {
			myData.closeConnection();
		}
		return result;
	}
	
	public boolean insertEdit(String tablevalue,String tabletext,String bz,String id){
		boolean result=false;

		DataConfig myData = new DataConfig();
		try {
			myData.openConnection();
			myData.beginTransaction();
			String sql1 ="update s_q_tablelist set tabletext='" + tabletext + "',tablevalue='" + tablevalue + "',bz='" + bz + "' where id='" + id + "'";
			myData.addBatch(sql1);
			if(myData.commit()){
				result=true;
			}else{
				result=false;
			}
			myData.endTransaction();
		} catch (SQLException e) {
			e.printStackTrace();
		} finally {
			myData.closeConnection();
		}
		return result;
	}
		
	public InsertActionBean insertSelectEdit(String id) {
		InsertActionBean bean = new InsertActionBean();
		DataConfig myData = new DataConfig();
		try {
			myData.openConnection();
			String sql="select tabletext,tablevalue,bz from s_q_tablelist where id=" + id + ";";
            ResultSet rs = myData
                    .executeQuery(sql);
            while (rs.next()) {
				bean.setTablevalue(rs.getString("tablevalue"));
				bean.setTabletext(rs.getString("tabletext"));
				bean.setBz(rs.getString("bz"));
            }
		} catch (SQLException e) {
			e.printStackTrace();
		} finally {
			myData.closeConnection();
		}
        return bean;
    }
    

	
	public boolean delete(String[] id){
		boolean result=false;

		DataConfig myData = new DataConfig();
		try {
			myData.openConnection();
			myData.beginTransaction();
			
			for(int i=0;i<id.length;i++){
				
				myData.addBatch("delete from  s_q_tablelist where  id ='"+id[i]+"'");
		
			}
			
			if(myData.commit()){
				result=true;
			}else{
				result=false;
			}
			myData.endTransaction();
		} catch (SQLException e) {
			e.printStackTrace();
		} finally {
			myData.closeConnection();
		}
		return result;
	}
}

