/*
*Generated by LiuRunze. 2009-06-09 18:02:15
*/
package com.genius.search.searchtype;

import java.util.ArrayList;

import org.genius.power.IPower;

import com.genius.search.searchtype.actionbean.*;;

public interface ISearchtype extends IPower {
	
	public int getTotalSize();

	public void setTotalSize(int totalSize);

	public String getSelectSql();

	public void setSelectSql(String selectSql);

	public ArrayList select(int pageNo, String orderField, String orderType, String searchField,String searchValue,String filter);
	
	
	
	
	
	
	
	public InsertActionBean insertSelectEdit(String searchid);
	
	public boolean insertNew(String searchparentid,String searchname);public ArrayList searchparentidInsertSelect();
	
	public boolean insertEdit(String searchparentid,String searchid,String searchname);
	
	
	
	
	
	
	
	
	
	
	
	
	
	public boolean delete(String[] id);
	
	
	
	

}
