/*
*Generated by GeniusPlatform. 2016-05-06 10:03:56
*/
package com.genius.BOSS.PCbar.actionbean;

public class InsertActionBean {
	
	private String id;
	
	private String resource_id;
	
	private String img_url;
	
	private String dest_type;
	
	private String reource_param;
	
	private String resource_order;
	
	private String is_delete;
	
	private String show_type;
	
	private String resource_name;
	
	private String show_position;
	
	private String resource_type;
	
	private String crreate_time;
	
	private String create_user;
	
	private String modify_time;
	
	private String modify_user;

		
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}
	
	public String getResource_id() {
		return resource_id;
	}

	public void setResource_id(String resource_id) {
		this.resource_id = resource_id;
	}
	
	public String getImg_url() {
		return img_url;
	}

	public void setImg_url(String img_url) {
		this.img_url = img_url;
	}
	
	public String getDest_type() {
		return dest_type;
	}

	public void setDest_type(String dest_type) {
		this.dest_type = dest_type;
	}
	
	public String getReource_param() {
		return reource_param;
	}

	public void setReource_param(String reource_param) {
		this.reource_param = reource_param;
	}
	
	public String getResource_order() {
		return resource_order;
	}

	public void setResource_order(String resource_order) {
		this.resource_order = resource_order;
	}
	
	public String getIs_delete() {
		return is_delete;
	}

	public void setIs_delete(String is_delete) {
		this.is_delete = is_delete;
	}
	
	public String getShow_type() {
		return show_type;
	}

	public void setShow_type(String show_type) {
		this.show_type = show_type;
	}
	
	public String getResource_name() {
		return resource_name;
	}

	public void setResource_name(String resource_name) {
		this.resource_name = resource_name;
	}
	
	public String getShow_position() {
		return show_position;
	}

	public void setShow_position(String show_position) {
		this.show_position = show_position;
	}
	
	public String getResource_type() {
		return resource_type;
	}

	public void setResource_type(String resource_type) {
		this.resource_type = resource_type;
	}
	
	public String getCrreate_time() {
		return crreate_time;
	}

	public void setCrreate_time(String crreate_time) {
		this.crreate_time = crreate_time;
	}
	
	public String getCreate_user() {
		return create_user;
	}

	public void setCreate_user(String create_user) {
		this.create_user = create_user;
	}
	
	public String getModify_time() {
		return modify_time;
	}

	public void setModify_time(String modify_time) {
		this.modify_time = modify_time;
	}
	
	public String getModify_user() {
		return modify_user;
	}

	public void setModify_user(String modify_user) {
		this.modify_user = modify_user;
	}


}
