/*
*Generated by LiuRunze. 2016-04-09 15:08:42
*/
package com.genius.BOSS.b_user.action;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.jdom.Document;
import org.jdom.Element;
import org.jdom.output.Format;
import org.jdom.output.XMLOutputter;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.Controller;

import com.genius.BOSS.b_user.IB_user;
import com.genius.BOSS.b_user.actionbean.*;

public final class InsertSelectPrintAction implements Controller {
	public ModelAndView handleRequest(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
		HttpSession session = request.getSession();
		
		if (session.getAttribute("login") == null
				|| (!session.getAttribute("login").equals("true"))) {
			Element root = new Element("entity");
			
			Element actionState = new Element("actionState");
			Element fieldState = new Element("field");
			fieldState.setAttribute("name", "state");
			fieldState.setAttribute("value", "noSession");
			actionState.addContent(fieldState);

			root.addContent(actionState);
			Document doc = new Document(root);
			response.setContentType("application/xml;charset=GB2312");
			Format format = Format.getPrettyFormat();
			format.setEncoding("GB2312");
			XMLOutputter outer = new XMLOutputter(format);
			outer.output(doc, response.getWriter());

			return null;
		}
		
				String id = request.getParameter("id");

		
		ApplicationContext context = new ClassPathXmlApplicationContext(
				"applicationContext.xml");

		IB_user b_user = (IB_user) context
				.getBean("b_userProxy");
		b_user.setSId(session.getAttribute("userId").toString());
		
		InsertActionBean bean = new InsertActionBean();
		bean = b_user.insertSelectEdit(id);
		
		Element root = new Element("entity");
		Element row = new Element("row");
	
		
		Element field0 = new Element("field");
		field0.setAttribute("name", "id");
		field0.setAttribute("value", id);
		row.addContent(field0);
		
		Element field1 = new Element("field");
		field1.setAttribute("name", "account");
		field1.setAttribute("value", bean.getAccount()==null?"":bean.getAccount());
		row.addContent(field1);
		
		Element field2 = new Element("field");
		field2.setAttribute("name", "name");
		field2.setAttribute("value", bean.getName()==null?"":bean.getName());
		row.addContent(field2);
		
		Element field3 = new Element("field");
		field3.setAttribute("name", "email");
		field3.setAttribute("value", bean.getEmail()==null?"":bean.getEmail());
		row.addContent(field3);
		
		Element field4 = new Element("field");
		field4.setAttribute("name", "phone_no");
		field4.setAttribute("value", bean.getPhone_no()==null?"":bean.getPhone_no());
		row.addContent(field4);
		
		Element field5 = new Element("field");
		field5.setAttribute("name", "password");
		field5.setAttribute("value", bean.getPassword()==null?"":bean.getPassword());
		row.addContent(field5);
		
		Element field6 = new Element("field");
		field6.setAttribute("name", "old_password");
		field6.setAttribute("value", bean.getOld_password()==null?"":bean.getOld_password());
		row.addContent(field6);
		
		Element field7 = new Element("field");
		field7.setAttribute("name", "head_img");
		field7.setAttribute("value", bean.getHead_img()==null?"":bean.getHead_img());
		row.addContent(field7);
		
		Element field8 = new Element("field");
		field8.setAttribute("name", "sex");
		field8.setAttribute("value", bean.getSex()==null?"":bean.getSex());
		row.addContent(field8);
		
		Element field9 = new Element("field");
		field9.setAttribute("name", "idcard_img");
		field9.setAttribute("value", bean.getIdcard_img()==null?"":bean.getIdcard_img());
		row.addContent(field9);
		
		Element field10 = new Element("field");
		field10.setAttribute("name", "id_card_no");
		field10.setAttribute("value", bean.getId_card_no()==null?"":bean.getId_card_no());
		row.addContent(field10);
		
		Element field11 = new Element("field");
		field11.setAttribute("name", "birthday");
		field11.setAttribute("value", bean.getBirthday()==null?"":bean.getBirthday());
		row.addContent(field11);
		
		Element field12 = new Element("field");
		field12.setAttribute("name", "role");
		field12.setAttribute("value", bean.getRole()==null?"":bean.getRole());
		row.addContent(field12);
		
		Element field13 = new Element("field");
		field13.setAttribute("name", "register_time");
		field13.setAttribute("value", bean.getRegister_time()==null?"":bean.getRegister_time());
		row.addContent(field13);
		
		Element field14 = new Element("field");
		field14.setAttribute("name", "is_identify");
		field14.setAttribute("value", bean.getIs_identify()==null?"":bean.getIs_identify());
		row.addContent(field14);
		
		Element field15 = new Element("field");
		field15.setAttribute("name", "preference");
		field15.setAttribute("value", bean.getPreference()==null?"":bean.getPreference());
		row.addContent(field15);
		
		Element field16 = new Element("field");
		field16.setAttribute("name", "status");
		field16.setAttribute("value", bean.getStatus()==null?"":bean.getStatus());
		row.addContent(field16);
		
		Element field17 = new Element("field");
		field17.setAttribute("name", "modify_time");
		field17.setAttribute("value", bean.getModify_time()==null?"":bean.getModify_time());
		row.addContent(field17);
		
		Element field18 = new Element("field");
		field18.setAttribute("name", "point");
		field18.setAttribute("value", bean.getPoint()==null?"":bean.getPoint());
		row.addContent(field18);
		
		Element field19 = new Element("field");
		field19.setAttribute("name", "credit");
		field19.setAttribute("value", bean.getCredit()==null?"":bean.getCredit());
		row.addContent(field19);
		
		Element field20 = new Element("field");
		field20.setAttribute("name", "brief");
		field20.setAttribute("value", bean.getBrief()==null?"":bean.getBrief());
		row.addContent(field20);
		
		Element field21 = new Element("field");
		field21.setAttribute("name", "skilled_fields");
		field21.setAttribute("value", bean.getSkilled_fields()==null?"":bean.getSkilled_fields());
		row.addContent(field21);
		
		Element field22 = new Element("field");
		field22.setAttribute("name", "cert_img");
		field22.setAttribute("value", bean.getCert_img()==null?"":bean.getCert_img());
		row.addContent(field22);
		
		Element field23 = new Element("field");
		field23.setAttribute("name", "college");
		field23.setAttribute("value", bean.getCollege()==null?"":bean.getCollege());
		row.addContent(field23);
		
		Element field24 = new Element("field");
		field24.setAttribute("name", "society");
		field24.setAttribute("value", bean.getSociety()==null?"":bean.getSociety());
		row.addContent(field24);
		
		Element field25 = new Element("field");
		field25.setAttribute("name", "hospital");
		field25.setAttribute("value", bean.getHospital()==null?"":bean.getHospital());
		row.addContent(field25);
		
		Element field26 = new Element("field");
		field26.setAttribute("name", "department");
		field26.setAttribute("value", bean.getDepartment()==null?"":bean.getDepartment());
		row.addContent(field26);
		
		Element field27 = new Element("field");
		field27.setAttribute("name", "job_title");
		field27.setAttribute("value", bean.getJob_title()==null?"":bean.getJob_title());
		row.addContent(field27);
		
		Element field28 = new Element("field");
		field28.setAttribute("name", "section");
		field28.setAttribute("value", bean.getSection()==null?"":bean.getSection());
		row.addContent(field28);
		
		Element field29 = new Element("field");
		field29.setAttribute("name", "liaisons");
		field29.setAttribute("value", bean.getLiaisons()==null?"":bean.getLiaisons());
		row.addContent(field29);
		
		Element field30 = new Element("field");
		field30.setAttribute("name", "area");
		field30.setAttribute("value", bean.getArea()==null?"":bean.getArea());
		row.addContent(field30);
		
		root.addContent(row);
		
		Element actionState = new Element("actionState");
		Element fieldState = new Element("field");
		fieldState.setAttribute("name", "state");
		fieldState.setAttribute("value", "session");
		actionState.addContent(fieldState);
		root.addContent(actionState);

		Document doc = new Document(root);
		response.setContentType("application/xml;charset=GB2312");
		Format format = Format.getPrettyFormat();
		format.setEncoding("GB2312");
		XMLOutputter outer = new XMLOutputter(format);
		outer.output(doc, response.getWriter());

		return null;
		
	}
}
