/*
*Generated by LiuRunze. 2016-04-09 15:08:42
*/
package com.genius.BOSS.b_user.action;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.log4j.Logger;
import org.jdom.Document;
import org.jdom.Element;
import org.jdom.output.Format;
import org.jdom.output.XMLOutputter;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.Controller;

import com.genius.BOSS.b_user.IB_user;
import com.genius.BOSS.b_user.actionbean.*;

public final class SectionSelectAction implements Controller {
	public ModelAndView handleRequest(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
		HttpSession session = request.getSession();

		ApplicationContext context = new ClassPathXmlApplicationContext(
				"applicationContext.xml");

		IB_user b_user = (IB_user) context
				.getBean("b_userProxy");
		b_user.setSId(session.getAttribute("userId").toString());
		ArrayList sectionList=new ArrayList();
		sectionList=b_user.sectionInsertSelect(); 
		
		Element root = new Element("entity");
		Iterator it = sectionList.iterator();

		while (it.hasNext()) {
			SectionActionBean bean = (SectionActionBean) it.next();
			Element row = new Element("row");
			Element field1 = new Element("field");
			field1.setAttribute("name", "value");
			field1.setAttribute("value", bean.getZhi());
			row.addContent(field1);
			Element field2 = new Element("field");
			field2.setAttribute("name", "field");
			field2.setAttribute("value", bean.getXianshi());
			row.addContent(field2);
			root.addContent(row);
			bean = null;
		}
		Document doc = new Document(root);
		response.setContentType("application/xml;charset=GB2312");
		Format format = Format.getPrettyFormat();
		format.setEncoding("GB2312");
		XMLOutputter outer = new XMLOutputter(format);
		outer.output(doc, response.getWriter());

		return null;
	}
}

