/*
*Generated by GeniusPlatform. 2016-05-06 10:03:56
*/
package com.genius.BOSS.medical_r;

import java.util.*;

import org.genius.power.IPower;

import com.genius.BOSS.medical_r.actionbean.*;;

public interface IMedical_r extends IPower {
	
	public int getTotalSize();	
	public int getTotalPageCount();
	public void setTotalSize(int totalSize);
	public String getSelectSql();
	public void setSelectSql(String selectSql);
	public ArrayList select(int pageNo, String orderField, String orderType, String searchField,String searchValue, String pager,String filter);
		
		
		
	public InsertActionBean insertSelectEdit(String ID);	
	public boolean insertNew(String DISCRIBE,String DISEASE,String case_imgs,String NAME,String RECIEVE_USER_ID,String SECTION,String SOLVE_CONTENT,String AGE,String STATE,String SOLVE_TIME,String CREATE_USER_ID,String is_jump_ask,String SEX,String CREATE_TIME);	
	public boolean insertEdit(String DISCRIBE,String DISEASE,String case_imgs,String NAME,String RECIEVE_USER_ID,String SECTION,String SOLVE_CONTENT,String AGE,String STATE,String SOLVE_TIME,String ID,String CREATE_USER_ID,String is_jump_ask,String SEX,String CREATE_TIME);	
		
		
		
		
		
		
	public boolean delete(String[] id);	
		
		
	

}
