/*
*Generated by GeniusPlatform. 2016-05-06 10:03:56
*/
package com.genius.BOSS.medical_j;

import java.util.*;

import org.genius.power.IPower;

import com.genius.BOSS.medical_j.actionbean.*;;

public interface IMedical_j extends IPower {
	
	public int getTotalSize();	
	public int getTotalPageCount();
	public void setTotalSize(int totalSize);
	public String getSelectSql();
	public void setSelectSql(String selectSql);
	public ArrayList select(int pageNo, String orderField, String orderType, String searchField,String searchValue, String pager,String filter);
		
		
		
	public InsertActionBean insertSelectEdit(String id);	
	public boolean insertNew(String create_time,String modify_time,String case_id,String content,String user_id);	
	public boolean insertEdit(String create_time,String modify_time,String case_id,String content,String id,String user_id);	
		
		
		
		
		
		
	public boolean delete(String[] id);	
		
		
	

}
