/*
*Generated by GeniusPlatform. 2016-05-06 10:03:56
*/
package com.genius.BOSS.APPbar.action;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.jdom.Document;
import org.jdom.Element;
import org.jdom.output.Format;
import org.jdom.output.XMLOutputter;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.Controller;

import org.genius.util.*;
import com.genius.BOSS.APPbar.IAPPbar;

public final class InsertEditAction implements Controller {
	public ModelAndView handleRequest(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {

		HttpSession session = request.getSession();
		
		if (session.getAttribute("login") == null
				|| (!session.getAttribute("login").equals("true"))) {
			Element root = new Element("entity");
			
			Element actionState = new Element("actionState");
			Element fieldState = new Element("field");
			fieldState.setAttribute("name", "state");
			fieldState.setAttribute("value", "noSession");
			actionState.addContent(fieldState);

			root.addContent(actionState);
			Document doc = new Document(root);
			response.setContentType("application/xml;charset=GB2312");
			Format format = Format.getPrettyFormat();
			format.setEncoding("GB2312");
			XMLOutputter outer = new XMLOutputter(format);
			outer.output(doc, response.getWriter());

			return null;
		}
		
		String success = "true";

		String id = java.net.URLDecoder.decode(request.getParameter("id"),"UTF-8");
		String resource_id = java.net.URLDecoder.decode(request.getParameter("resource_id"),"UTF-8");
		String img_url = java.net.URLDecoder.decode(request.getParameter("img_url"),"UTF-8");
		String dest_type = java.net.URLDecoder.decode(request.getParameter("dest_type"),"UTF-8");
		String reource_param = java.net.URLDecoder.decode(request.getParameter("reource_param"),"UTF-8");
		String resource_order = java.net.URLDecoder.decode(request.getParameter("resource_order"),"UTF-8");
		String is_delete = java.net.URLDecoder.decode(request.getParameter("is_delete"),"UTF-8");
		String show_type = java.net.URLDecoder.decode(request.getParameter("show_type"),"UTF-8");
		String resource_name = java.net.URLDecoder.decode(request.getParameter("resource_name"),"UTF-8");
		String show_position = java.net.URLDecoder.decode(request.getParameter("show_position"),"UTF-8");
		String resource_type = java.net.URLDecoder.decode(request.getParameter("resource_type"),"UTF-8");
		String crreate_time = java.net.URLDecoder.decode(request.getParameter("crreate_time"),"UTF-8");
		String create_user = java.net.URLDecoder.decode(request.getParameter("create_user"),"UTF-8");
		String modify_time = java.net.URLDecoder.decode(request.getParameter("modify_time"),"UTF-8");
		String modify_user = java.net.URLDecoder.decode(request.getParameter("modify_user"),"UTF-8");


		ApplicationContext context = new ClassPathXmlApplicationContext(
				"applicationContext.xml");

		IAPPbar APPbar = (IAPPbar) context
				.getBean("APPbarProxy");
		APPbar.setSId(session.getAttribute("userId").toString());
		try {
			if (APPbar.insertEdit(show_position,img_url,resource_type,resource_order,resource_name,modify_user,dest_type,modify_time,is_delete,show_type,id,reource_param,create_user,resource_id,crreate_time)) {
				success = "true";
			} else {
				success = "false";
			}
		} catch (NullPointerException e) {
			success = "noPower";
		}

		Element root = new Element("entity");
		Element row = new Element("row");
		Element field1 = new Element("field");
		field1.setAttribute("name", "success");
		field1.setAttribute("value", success);
		row.addContent(field1);

		root.addContent(row);
		
		Element actionState = new Element("actionState");
		Element fieldState = new Element("field");
		fieldState.setAttribute("name", "state");
		fieldState.setAttribute("value", "session");
		actionState.addContent(fieldState);
		root.addContent(actionState);

		Document doc = new Document(root);
		response.setContentType("application/xml;charset=GB2312");
		Format format = Format.getPrettyFormat();
		format.setEncoding("GB2312");
		XMLOutputter outer = new XMLOutputter(format);
		outer.output(doc, response.getWriter());

		return null;
	}
}

