/*
*Generated by LiuRunze. 2016-04-09 15:08:42
*/
package com.genius.BOSS.b_user.actionbean;

public class InsertActionBean {
	
	private String id;
	
	private String account;
	
	private String name;
	
	private String email;
	
	private String phone_no;
	
	private String password;
	
	private String old_password;
	
	private String head_img;
	
	private String sex;
	
	private String idcard_img;
	
	private String id_card_no;
	
	private String birthday;
	
	private String role;
	
	private String register_time;
	
	private String is_identify;
	
	private String preference;
	
	private String status;
	
	private String modify_time;
	
	private String point;
	
	private String credit;
	
	private String brief;
	
	private String skilled_fields;
	
	private String cert_img;
	
	private String college;
	
	private String society;
	
	private String hospital;
	
	private String department;
	
	private String job_title;
	
	private String section;
	
	private String liaisons;
	
	private String area;

		
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}
	
	public String getAccount() {
		return account;
	}

	public void setAccount(String account) {
		this.account = account;
	}
	
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	
	public String getPhone_no() {
		return phone_no;
	}

	public void setPhone_no(String phone_no) {
		this.phone_no = phone_no;
	}
	
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
	public String getOld_password() {
		return old_password;
	}

	public void setOld_password(String old_password) {
		this.old_password = old_password;
	}
	
	public String getHead_img() {
		return head_img;
	}

	public void setHead_img(String head_img) {
		this.head_img = head_img;
	}
	
	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}
	
	public String getIdcard_img() {
		return idcard_img;
	}

	public void setIdcard_img(String idcard_img) {
		this.idcard_img = idcard_img;
	}
	
	public String getId_card_no() {
		return id_card_no;
	}

	public void setId_card_no(String id_card_no) {
		this.id_card_no = id_card_no;
	}
	
	public String getBirthday() {
		return birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}
	
	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}
	
	public String getRegister_time() {
		return register_time;
	}

	public void setRegister_time(String register_time) {
		this.register_time = register_time;
	}
	
	public String getIs_identify() {
		return is_identify;
	}

	public void setIs_identify(String is_identify) {
		this.is_identify = is_identify;
	}
	
	public String getPreference() {
		return preference;
	}

	public void setPreference(String preference) {
		this.preference = preference;
	}
	
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	
	public String getModify_time() {
		return modify_time;
	}

	public void setModify_time(String modify_time) {
		this.modify_time = modify_time;
	}
	
	public String getPoint() {
		return point;
	}

	public void setPoint(String point) {
		this.point = point;
	}
	
	public String getCredit() {
		return credit;
	}

	public void setCredit(String credit) {
		this.credit = credit;
	}
	
	public String getBrief() {
		return brief;
	}

	public void setBrief(String brief) {
		this.brief = brief;
	}
	
	public String getSkilled_fields() {
		return skilled_fields;
	}

	public void setSkilled_fields(String skilled_fields) {
		this.skilled_fields = skilled_fields;
	}
	
	public String getCert_img() {
		return cert_img;
	}

	public void setCert_img(String cert_img) {
		this.cert_img = cert_img;
	}
	
	public String getCollege() {
		return college;
	}

	public void setCollege(String college) {
		this.college = college;
	}
	
	public String getSociety() {
		return society;
	}

	public void setSociety(String society) {
		this.society = society;
	}
	
	public String getHospital() {
		return hospital;
	}

	public void setHospital(String hospital) {
		this.hospital = hospital;
	}
	
	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}
	
	public String getJob_title() {
		return job_title;
	}

	public void setJob_title(String job_title) {
		this.job_title = job_title;
	}
	
	public String getSection() {
		return section;
	}

	public void setSection(String section) {
		this.section = section;
	}
	
	public String getLiaisons() {
		return liaisons;
	}

	public void setLiaisons(String liaisons) {
		this.liaisons = liaisons;
	}
	
	public String getArea() {
		return area;
	}

	public void setArea(String area) {
		this.area = area;
	}


}
