/*
*Generated by LiuRunze. 2016-04-09 15:08:42
*/
package com.genius.BOSS.b_user.actionbean;

public class LiaisonsActionBean {
	
	private String xianshi;
	
	private String zhi;

		
	public String getXianshi() {
		return xianshi;
	}

	public void setXianshi(String xianshi) {
		this.xianshi = xianshi;
	}
	
	public String getZhi() {
		return zhi;
	}

	public void setZhi(String zhi) {
		this.zhi = zhi;
	}


}
