/*
*Generated by LiuRunze. 2009-06-09 18:02:15
*/
package com.genius.search.tablelist.action;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.Controller;

import com.genius.adminmanager.login.Login;
import com.genius.search.tablelist.TablelistExt;

public final class InsertNewAction implements Controller {
	public ModelAndView handleRequest(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {

		request.setCharacterEncoding("gbk");
		response.setCharacterEncoding("gbk");
		HttpSession session = request.getSession();
		if (session.getAttribute("userName") == null
				|| !(Login.loginAdmin(session.getAttribute("userName")
						.toString(), session.getAttribute("roleId").toString()))) {
			return new ModelAndView("../error.jsp");
		}

		String tablevalue = request.getParameter("tablevalue");
		String tabletext = request.getParameter("tabletext");
		String bz = request.getParameter("bz");
			
		TablelistExt tablelistExt = new TablelistExt();
		tablelistExt.insertNew(tablevalue, tabletext, bz);
		return new ModelAndView("tl_select.do");
	}
}

