/*
*Generated by LiuRunze. 2009-06-09 18:02:15
*/
package com.genius.search.tablelist.action;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.Controller;

import com.genius.adminmanager.login.Login;
import com.genius.search.tablelist.TablelistExt;
import com.genius.search.tablelist.actionbean.InsertActionBean;

public final class InsertSelectEditAction implements Controller {
	public ModelAndView handleRequest(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
			HttpSession session = request.getSession();
			if (session.getAttribute("userName") == null
					|| !(Login.loginAdmin(session.getAttribute("userName")
							.toString(), session.getAttribute("roleId").toString()))) {
				return new ModelAndView("../error.jsp");
			}
			
			String myId = request.getParameter("id");

			TablelistExt tablelistExt = new TablelistExt();
			InsertActionBean bean = tablelistExt.insertSelectEdit(myId);
			
			request.setAttribute("bean", bean);
			request.setAttribute("updateid", myId);
			return new ModelAndView("tl_insert.jsp?acttype=update");
	}
}
