/*
*Generated by LiuRunze. 2009-06-09 18:02:15
*/
package com.genius.search.tablelist.actionbean;

public class SelectActionBean {
	
	private String id;
	
	private String tablevalue;
	
	private String tabletext;
	
	private String bz;

		
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}
	
	public String getTablevalue() {
		return tablevalue;
	}

	public void setTablevalue(String tablevalue) {
		this.tablevalue = tablevalue;
	}
	
	public String getTabletext() {
		return tabletext;
	}

	public void setTabletext(String tabletext) {
		this.tabletext = tabletext;
	}
	
	public String getBz() {
		return bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}


}
