/*
*Generated by GeniusPlatform. 2016-05-06 10:03:56
*/
package com.genius.BOSS.hospital_m;

import java.util.*;

import org.genius.power.IPower;

import com.genius.BOSS.hospital_m.actionbean.*;;

public interface IHospital_m extends IPower {
	
	public int getTotalSize();	
	public int getTotalPageCount();
	public void setTotalSize(int totalSize);
	public String getSelectSql();
	public void setSelectSql(String selectSql);
	public ArrayList select(int pageNo, String orderField, String orderType, String searchField,String searchValue, String pager,String filter);
		
		
		
	public InsertActionBean insertSelectEdit(String id);	
	public boolean insertNew(String province,String city,String content,String name,String phone,String alias,String level,String address);	
	public boolean insertEdit(String province,String city,String content,String name,String id,String phone,String alias,String level,String address);	
		
		
		
		
		
		
	public boolean delete(String[] id);	
		
		
	

}
