/*
*Generated by GeniusPlatform. 2016-04-11 15:57:14
*/
package com.genius.BOSS.verify.actionbean;

public class SectionActionBean {
	
	private String xianshi;
	
	private String zhi;

		
	public String getXianshi() {
		return xianshi;
	}

	public void setXianshi(String xianshi) {
		this.xianshi = xianshi;
	}
	
	public String getZhi() {
		return zhi;
	}

	public void setZhi(String zhi) {
		this.zhi = zhi;
	}


}
