/*
*Generated by GeniusPlatform. 2016-04-11 15:57:14
*/
package com.genius.BOSS.verify.actionbean;

public class SelectActionBean {
	
	private String id;
	
	private String name;
	
	private String id_card_no;
	
	private String phone_no;
	
	private String account;
	
	private String role;
	
	private String sex;
	
	private String job_title;
	
	private String hospital;
	
	private String department;
	
	private String society;
	
	private String section;
	
	private String liaisons;
	
	private String point;
	
	private String credit;
	
	private String register_time;
	
	private String email;
	
	private String birthday;
	
	private String college;
	
	private String is_identify;
	
	private String area;

		
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}
	
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	public String getId_card_no() {
		return id_card_no;
	}

	public void setId_card_no(String id_card_no) {
		this.id_card_no = id_card_no;
	}
	
	public String getPhone_no() {
		return phone_no;
	}

	public void setPhone_no(String phone_no) {
		this.phone_no = phone_no;
	}
	
	public String getAccount() {
		return account;
	}

	public void setAccount(String account) {
		this.account = account;
	}
	
	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}
	
	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}
	
	public String getJob_title() {
		return job_title;
	}

	public void setJob_title(String job_title) {
		this.job_title = job_title;
	}
	
	public String getHospital() {
		return hospital;
	}

	public void setHospital(String hospital) {
		this.hospital = hospital;
	}
	
	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}
	
	public String getSociety() {
		return society;
	}

	public void setSociety(String society) {
		this.society = society;
	}
	
	public String getSection() {
		return section;
	}

	public void setSection(String section) {
		this.section = section;
	}
	
	public String getLiaisons() {
		return liaisons;
	}

	public void setLiaisons(String liaisons) {
		this.liaisons = liaisons;
	}
	
	public String getPoint() {
		return point;
	}

	public void setPoint(String point) {
		this.point = point;
	}
	
	public String getCredit() {
		return credit;
	}

	public void setCredit(String credit) {
		this.credit = credit;
	}
	
	public String getRegister_time() {
		return register_time;
	}

	public void setRegister_time(String register_time) {
		this.register_time = register_time;
	}
	
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	
	public String getBirthday() {
		return birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}
	
	public String getCollege() {
		return college;
	}

	public void setCollege(String college) {
		this.college = college;
	}
	
	public String getIs_identify() {
		return is_identify;
	}

	public void setIs_identify(String is_identify) {
		this.is_identify = is_identify;
	}
	
	public String getArea() {
		return area;
	}

	public void setArea(String area) {
		this.area = area;
	}


}
