/*
*Generated by GeniusPlatform. 2016-05-06 10:03:56
*/
package com.genius.BOSS.medical_r.actionbean;

public class SelectActionBean {
	
	private String ID;
	
	private String NAME;
	
	private String SEX;
	
	private String AGE;
	
	private String DISEASE;
	
	private String DISCRIBE;
	
	private String SECTION;
	
	private String CREATE_USER_ID;
	
	private String CREATE_TIME;
	
	private String STATE;
	
	private String RECIEVE_USER_ID;
	
	private String SOLVE_TIME;
	
	private String is_jump_ask;

		
	public String getID() {
		return ID;
	}

	public void setID(String ID) {
		this.ID = ID;
	}
	
	public String getNAME() {
		return NAME;
	}

	public void setNAME(String NAME) {
		this.NAME = NAME;
	}
	
	public String getSEX() {
		return SEX;
	}

	public void setSEX(String SEX) {
		this.SEX = SEX;
	}
	
	public String getAGE() {
		return AGE;
	}

	public void setAGE(String AGE) {
		this.AGE = AGE;
	}
	
	public String getDISEASE() {
		return DISEASE;
	}

	public void setDISEASE(String DISEASE) {
		this.DISEASE = DISEASE;
	}
	
	public String getDISCRIBE() {
		return DISCRIBE;
	}

	public void setDISCRIBE(String DISCRIBE) {
		this.DISCRIBE = DISCRIBE;
	}
	
	public String getSECTION() {
		return SECTION;
	}

	public void setSECTION(String SECTION) {
		this.SECTION = SECTION;
	}
	
	public String getCREATE_USER_ID() {
		return CREATE_USER_ID;
	}

	public void setCREATE_USER_ID(String CREATE_USER_ID) {
		this.CREATE_USER_ID = CREATE_USER_ID;
	}
	
	public String getCREATE_TIME() {
		return CREATE_TIME;
	}

	public void setCREATE_TIME(String CREATE_TIME) {
		this.CREATE_TIME = CREATE_TIME;
	}
	
	public String getSTATE() {
		return STATE;
	}

	public void setSTATE(String STATE) {
		this.STATE = STATE;
	}
	
	public String getRECIEVE_USER_ID() {
		return RECIEVE_USER_ID;
	}

	public void setRECIEVE_USER_ID(String RECIEVE_USER_ID) {
		this.RECIEVE_USER_ID = RECIEVE_USER_ID;
	}
	
	public String getSOLVE_TIME() {
		return SOLVE_TIME;
	}

	public void setSOLVE_TIME(String SOLVE_TIME) {
		this.SOLVE_TIME = SOLVE_TIME;
	}
	
	public String getIs_jump_ask() {
		return is_jump_ask;
	}

	public void setIs_jump_ask(String is_jump_ask) {
		this.is_jump_ask = is_jump_ask;
	}


}
