/*
*Generated by GeniusPlatform. 2016-05-06 10:03:56
*/
package com.genius.BOSS.medical_j.action;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.jdom.Document;
import org.jdom.Element;
import org.jdom.output.Format;
import org.jdom.output.XMLOutputter;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.Controller;

import com.genius.BOSS.medical_j.IMedical_j;
import com.genius.BOSS.medical_j.actionbean.*;

public final class InsertSelectEditAction implements Controller {
	public ModelAndView handleRequest(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
		HttpSession session = request.getSession();
		
		if (session.getAttribute("login") == null
				|| (!session.getAttribute("login").equals("true"))) {
			Element root = new Element("entity");
			
			Element actionState = new Element("actionState");
			Element fieldState = new Element("field");
			fieldState.setAttribute("name", "state");
			fieldState.setAttribute("value", "noSession");
			actionState.addContent(fieldState);

			root.addContent(actionState);
			Document doc = new Document(root);
			response.setContentType("application/xml;charset=GB2312");
			Format format = Format.getPrettyFormat();
			format.setEncoding("GB2312");
			XMLOutputter outer = new XMLOutputter(format);
			outer.output(doc, response.getWriter());

			return null;
		}
		
				String id = request.getParameter("id");

		
		ApplicationContext context = new ClassPathXmlApplicationContext(
				"applicationContext.xml");

		IMedical_j medical_j = (IMedical_j) context
				.getBean("medical_jProxy");
		medical_j.setSId(session.getAttribute("userId").toString());
		
		InsertActionBean bean = new InsertActionBean();
		bean = medical_j.insertSelectEdit(id);
		
		Element root = new Element("entity");
		Element row = new Element("row");
		
		
		Element field0 = new Element("field");
		field0.setAttribute("name", "id");
		field0.setAttribute("value", id);
		row.addContent(field0);
		
		Element field1 = new Element("field");
		field1.setAttribute("name", "case_id");
		field1.setAttribute("value", bean.getCase_id()==null?"":bean.getCase_id());
		row.addContent(field1);
		
		Element field2 = new Element("field");
		field2.setAttribute("name", "user_id");
		field2.setAttribute("value", bean.getUser_id()==null?"":bean.getUser_id());
		row.addContent(field2);
		
		Element field3 = new Element("field");
		field3.setAttribute("name", "content");
		field3.setAttribute("value", bean.getContent()==null?"":bean.getContent());
		row.addContent(field3);
		
		Element field4 = new Element("field");
		field4.setAttribute("name", "create_time");
		field4.setAttribute("value", bean.getCreate_time()==null?"":bean.getCreate_time());
		row.addContent(field4);
		
		Element field5 = new Element("field");
		field5.setAttribute("name", "modify_time");
		field5.setAttribute("value", bean.getModify_time()==null?"":bean.getModify_time());
		row.addContent(field5);
		
		root.addContent(row);
		
		Element actionState = new Element("actionState");
		Element fieldState = new Element("field");
		fieldState.setAttribute("name", "state");
		fieldState.setAttribute("value", "session");
		actionState.addContent(fieldState);
		root.addContent(actionState);

		Document doc = new Document(root);
		response.setContentType("application/xml;charset=GB2312");
		Format format = Format.getPrettyFormat();
		format.setEncoding("GB2312");
		XMLOutputter outer = new XMLOutputter(format);
		outer.output(doc, response.getWriter());

		return null;
		
	}
}
