/*
*Generated by GeniusPlatform. 2016-04-11 15:57:15
*/
package com.genius.BOSS.verify.action;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.jdom.Document;
import org.jdom.Element;
import org.jdom.output.Format;
import org.jdom.output.XMLOutputter;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.Controller;

import org.genius.util.*;
import com.genius.BOSS.verify.IVerify;

public final class InsertNewAction implements Controller {
	public ModelAndView handleRequest(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {

		HttpSession session = request.getSession();
		
		if (session.getAttribute("login") == null
				|| (!session.getAttribute("login").equals("true"))) {
			Element root = new Element("entity");
			
			Element actionState = new Element("actionState");
			Element fieldState = new Element("field");
			fieldState.setAttribute("name", "state");
			fieldState.setAttribute("value", "noSession");
			actionState.addContent(fieldState);

			root.addContent(actionState);
			Document doc = new Document(root);
			response.setContentType("application/xml;charset=GB2312");
			Format format = Format.getPrettyFormat();
			format.setEncoding("GB2312");
			XMLOutputter outer = new XMLOutputter(format);
			outer.output(doc, response.getWriter());

			return null;
		}
		
		String success = "true";

		String account = java.net.URLDecoder.decode(request.getParameter("account"),"UTF-8");
		String name = java.net.URLDecoder.decode(request.getParameter("name"),"UTF-8");
		String phone_no = java.net.URLDecoder.decode(request.getParameter("phone_no"),"UTF-8");
		String head_img = java.net.URLDecoder.decode(request.getParameter("head_img"),"UTF-8");
		String sex = java.net.URLDecoder.decode(request.getParameter("sex"),"UTF-8");
		String idcard_img = java.net.URLDecoder.decode(request.getParameter("idcard_img"),"UTF-8");
		String id_card_no = java.net.URLDecoder.decode(request.getParameter("id_card_no"),"UTF-8");
		String birthday = java.net.URLDecoder.decode(request.getParameter("birthday"),"UTF-8");
		String role = java.net.URLDecoder.decode(request.getParameter("role"),"UTF-8");
		String register_time = java.net.URLDecoder.decode(request.getParameter("register_time"),"UTF-8");
		String is_identify = java.net.URLDecoder.decode(request.getParameter("is_identify"),"UTF-8");
		String status = java.net.URLDecoder.decode(request.getParameter("status"),"UTF-8");
		String modify_time = java.net.URLDecoder.decode(request.getParameter("modify_time"),"UTF-8");
		String point = java.net.URLDecoder.decode(request.getParameter("point"),"UTF-8");
		String credit = java.net.URLDecoder.decode(request.getParameter("credit"),"UTF-8");
		String brief = java.net.URLDecoder.decode(request.getParameter("brief"),"UTF-8");
brief=TextFormat.getSqlText(brief);
		String cert_img = java.net.URLDecoder.decode(request.getParameter("cert_img"),"UTF-8");
		String college = java.net.URLDecoder.decode(request.getParameter("college"),"UTF-8");
		String society = java.net.URLDecoder.decode(request.getParameter("society"),"UTF-8");
		String hospital = java.net.URLDecoder.decode(request.getParameter("hospital"),"UTF-8");
		String department = java.net.URLDecoder.decode(request.getParameter("department"),"UTF-8");
		String job_title = java.net.URLDecoder.decode(request.getParameter("job_title"),"UTF-8");
		String section = java.net.URLDecoder.decode(request.getParameter("section"),"UTF-8");
		String liaisons = java.net.URLDecoder.decode(request.getParameter("liaisons"),"UTF-8");
		String area = java.net.URLDecoder.decode(request.getParameter("area"),"UTF-8");


		ApplicationContext context = new ClassPathXmlApplicationContext(
				"applicationContext.xml");

		IVerify verify = (IVerify) context
				.getBean("verifyProxy");
		verify.setSId(session.getAttribute("userId").toString());
		try {
			if (verify.insertNew(department,birthday,point,section,id_card_no,role,account,idcard_img,job_title,cert_img,college,hospital,liaisons,credit,area,name,phone_no,brief,status,sex,modify_time,is_identify,head_img,register_time,society)) {
				success = "true";
			} else {
				success = "false";
			}
		} catch (NullPointerException e) {
			success = "noPower";
		}

		Element root = new Element("entity");
		Element row = new Element("row");
		Element field1 = new Element("field");
		field1.setAttribute("name", "success");
		field1.setAttribute("value", success);
		row.addContent(field1);

		root.addContent(row);
		
		Element actionState = new Element("actionState");
		Element fieldState = new Element("field");
		fieldState.setAttribute("name", "state");
		fieldState.setAttribute("value", "session");
		actionState.addContent(fieldState);
		root.addContent(actionState);

		Document doc = new Document(root);
		response.setContentType("application/xml;charset=GB2312");
		Format format = Format.getPrettyFormat();
		format.setEncoding("GB2312");
		XMLOutputter outer = new XMLOutputter(format);
		outer.output(doc, response.getWriter());

		return null;
	}
}

