/*
*Generated by LiuRunze. 2016-04-09 15:08:42
*/
package com.genius.BOSS.b_user;

import java.util.*;

import org.genius.power.IPower;

import com.genius.BOSS.b_user.actionbean.*;;

public interface IB_user extends IPower {
	
	public int getTotalSize();	
	public int getTotalPageCount();
	public void setTotalSize(int totalSize);
	public String getSelectSql();
	public void setSelectSql(String selectSql);
	public ArrayList select(int pageNo, String orderField, String orderType, String searchField,String searchValue, String pager,String filter);
		
		
		
	public InsertActionBean insertSelectEdit(String id);	
	public boolean insertNew(String department,String birthday,String point,String section,String id_card_no,String role,String account,String job_title,String idcard_img,String email,String preference,String cert_img,String college,String hospital,String liaisons,String credit,String area,String name,String phone_no,String password,String brief,String status,String sex,String old_password,String is_identify,String modify_time,String head_img,String skilled_fields,String register_time,String society);public ArrayList hospitalInsertSelect();public ArrayList departmentInsertSelect();public ArrayList job_titleInsertSelect();public ArrayList sectionInsertSelect();public ArrayList liaisonsInsertSelect();public ArrayList areaInsertSelect(String pid);	
	public boolean insertEdit(String department,String birthday,String point,String section,String id_card_no,String role,String account,String job_title,String idcard_img,String email,String preference,String cert_img,String college,String id,String hospital,String liaisons,String credit,String area,String name,String phone_no,String password,String brief,String status,String sex,String old_password,String is_identify,String modify_time,String head_img,String skilled_fields,String register_time,String society);	
		
		
		
		
		
		
	public boolean delete(String[] id);	
		
		
	

}
