/*
*Generated by LiuRunze. 2009-06-09 18:02:15
*/
package com.genius.search.tablefield;

import java.util.ArrayList;

import org.genius.power.IPower;

import com.genius.search.tablefield.actionbean.*;;

public interface ITablefield extends IPower {
	
	public int getTotalSize();

	public void setTotalSize(int totalSize);

	public String getSelectSql();

	public void setSelectSql(String selectSql);

	public ArrayList select(int pageNo, String orderField, String orderType, String searchField,String searchValue,String filter);
	
	
	
	
	
	
	
	public InsertActionBean insertSelectEdit(String id);
	
	public boolean insertNew(String oftable,String fieldtext,String fieldvalue,String fieldtype,String bz);public ArrayList oftableInsertSelect();
	
	public boolean insertEdit(String oftable,String fieldtext,String fieldvalue,String fieldtype,String bz,String id);
	
	
	
	
	
	
	
	
	
	
	
	
	
	public boolean delete(String[] id);
	
	
	
	

}
