/*
*Generated by LiuRunze. 2016-04-09 15:08:42
*/
package com.genius.BOSS.menu.action;

import java.io.IOException;
import java.util.Map;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.log4j.Logger;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.Controller;

import org.genius.power.Permission;

public class MenuAction implements Controller {
	public ModelAndView handleRequest(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
        HttpSession session = request.getSession();

        //Permission permission=new Permission();
        //Map map = permission.moduleMap(session.getAttribute("userId").toString());
        

        return new ModelAndView("/left.jsp");
    }
}
