/*
*Generated by GeniusPlatform. 2016-05-06 10:03:56
*/
package com.genius.BOSS.cdsy_v.actionbean;

public class InsertActionBean {
	
	private String id;
	
	private String user_id;
	
	private String operate_state;
	
	private String open_state;
	
	private String score;
	
	private String type;
	
	private String academic;
	
	private String create_user;
	
	private String modify_time;
	
	private String modify_user;
	
	private String department;
	
	private String title;
	
	private String audior_name;
	
	private String create_time;
	
	private String source;
	
	private String info;
	
	private String key_word;
	
	private String content;
	
	private String img_url;
	
	private String ucg;
	
	private String apply_state;
	
	private String rank_type;
	
	private String cover_img;
	
	private String attachment_id;

		
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}
	
	public String getUser_id() {
		return user_id;
	}

	public void setUser_id(String user_id) {
		this.user_id = user_id;
	}
	
	public String getOperate_state() {
		return operate_state;
	}

	public void setOperate_state(String operate_state) {
		this.operate_state = operate_state;
	}
	
	public String getOpen_state() {
		return open_state;
	}

	public void setOpen_state(String open_state) {
		this.open_state = open_state;
	}
	
	public String getScore() {
		return score;
	}

	public void setScore(String score) {
		this.score = score;
	}
	
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}
	
	public String getAcademic() {
		return academic;
	}

	public void setAcademic(String academic) {
		this.academic = academic;
	}
	
	public String getCreate_user() {
		return create_user;
	}

	public void setCreate_user(String create_user) {
		this.create_user = create_user;
	}
	
	public String getModify_time() {
		return modify_time;
	}

	public void setModify_time(String modify_time) {
		this.modify_time = modify_time;
	}
	
	public String getModify_user() {
		return modify_user;
	}

	public void setModify_user(String modify_user) {
		this.modify_user = modify_user;
	}
	
	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}
	
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}
	
	public String getAudior_name() {
		return audior_name;
	}

	public void setAudior_name(String audior_name) {
		this.audior_name = audior_name;
	}
	
	public String getCreate_time() {
		return create_time;
	}

	public void setCreate_time(String create_time) {
		this.create_time = create_time;
	}
	
	public String getSource() {
		return source;
	}

	public void setSource(String source) {
		this.source = source;
	}
	
	public String getInfo() {
		return info;
	}

	public void setInfo(String info) {
		this.info = info;
	}
	
	public String getKey_word() {
		return key_word;
	}

	public void setKey_word(String key_word) {
		this.key_word = key_word;
	}
	
	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}
	
	public String getImg_url() {
		return img_url;
	}

	public void setImg_url(String img_url) {
		this.img_url = img_url;
	}
	
	public String getUcg() {
		return ucg;
	}

	public void setUcg(String ucg) {
		this.ucg = ucg;
	}
	
	public String getApply_state() {
		return apply_state;
	}

	public void setApply_state(String apply_state) {
		this.apply_state = apply_state;
	}
	
	public String getRank_type() {
		return rank_type;
	}

	public void setRank_type(String rank_type) {
		this.rank_type = rank_type;
	}
	
	public String getCover_img() {
		return cover_img;
	}

	public void setCover_img(String cover_img) {
		this.cover_img = cover_img;
	}
	
	public String getAttachment_id() {
		return attachment_id;
	}

	public void setAttachment_id(String attachment_id) {
		this.attachment_id = attachment_id;
	}


}
