/*
*Generated by GeniusPlatform. 2016-05-06 10:03:56
*/
package com.genius.BOSS.cdsy_v.actionbean;

public class SelectActionBean {
	
	private String id;
	
	private String title;
	
	private String user_id;
	
	private String type;
	
	private String department;
	
	private String operate_state;
	
	private String open_state;
	
	private String score;
	
	private String academic;
	
	private String apply_state;
	
	private String create_user;
	
	private String create_time;
	
	private String audior_name;
	
	private String source;
	
	private String key_word;
	
	private String ucg;

		
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}
	
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}
	
	public String getUser_id() {
		return user_id;
	}

	public void setUser_id(String user_id) {
		this.user_id = user_id;
	}
	
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}
	
	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}
	
	public String getOperate_state() {
		return operate_state;
	}

	public void setOperate_state(String operate_state) {
		this.operate_state = operate_state;
	}
	
	public String getOpen_state() {
		return open_state;
	}

	public void setOpen_state(String open_state) {
		this.open_state = open_state;
	}
	
	public String getScore() {
		return score;
	}

	public void setScore(String score) {
		this.score = score;
	}
	
	public String getAcademic() {
		return academic;
	}

	public void setAcademic(String academic) {
		this.academic = academic;
	}
	
	public String getApply_state() {
		return apply_state;
	}

	public void setApply_state(String apply_state) {
		this.apply_state = apply_state;
	}
	
	public String getCreate_user() {
		return create_user;
	}

	public void setCreate_user(String create_user) {
		this.create_user = create_user;
	}
	
	public String getCreate_time() {
		return create_time;
	}

	public void setCreate_time(String create_time) {
		this.create_time = create_time;
	}
	
	public String getAudior_name() {
		return audior_name;
	}

	public void setAudior_name(String audior_name) {
		this.audior_name = audior_name;
	}
	
	public String getSource() {
		return source;
	}

	public void setSource(String source) {
		this.source = source;
	}
	
	public String getKey_word() {
		return key_word;
	}

	public void setKey_word(String key_word) {
		this.key_word = key_word;
	}
	
	public String getUcg() {
		return ucg;
	}

	public void setUcg(String ucg) {
		this.ucg = ucg;
	}


}
