/*
*Generated by LiuRunze. 2016-04-09 15:08:41
*/
package com.genius.BOSS.login;

import java.sql.ResultSet;
import java.sql.SQLException;

import org.genius.data.DataConfig;
import org.genius.util.DateFormat;

public class Login {

	public boolean check(String username, String password) {
		DataConfig myData = new DataConfig();
		boolean result = false;
		try {
			myData.openConnection();
			String sql = "select * from s_userinfo where username='"
					+ username + "' and sign='1'";
			ResultSet rs = myData.executeQuery(sql);
			while (rs.next()) {
				if (password.equals(rs.getString("password").trim())) {
					result = true;
				} else {
					result = false;
				}
			}
		} catch (SQLException e) {
			e.printStackTrace();
		} finally {
			myData.closeConnection();
		}
		return result;
	}
	
	public boolean log(String userId, String type) {

		boolean result = false;
		DataConfig myData = new DataConfig();
		myData.init();
		try {
			myData.openConnection();
			myData.beginTransaction();
			String sql1="";
			if(myData.databaseTypeid ==0){ //Database type 0??MicrosoftSqlServer
				sql1 = "insert into s_log_login(user_id,type,operate_time) values('"
					+ userId
					+ "','"
					+ type
					+ "','"
					+ DateFormat.getLongDateNow() + "')";
			}else if(myData.databaseTypeid ==1){ //Database type 1??Oracle
				sql1 = "insert into s_log_login(user_id,type,operate_time) values('"
					+ userId
					+ "','"
					+ type
					+ "',to_date('"
					+ DateFormat.getLongDateNow() + "','yyyy-mm-dd hh24:mi:ss'))";
			}else if(myData.databaseTypeid ==2){//mysql
				sql1 = "insert into s_log_login(user_id,type,operate_time) values('"
					+ userId
					+ "','"
					+ type
					+ "',to_date('"
					+ DateFormat.getLongDateNow() + "','yyyy-mm-dd hh24:mi:ss'))";
			}else{}
			
			myData.addBatch(sql1);

			if (myData.commit()) {
				result = true;
			} else {
				result = false;
			}

			myData.endTransaction();

		} catch (SQLException e) {
			e.printStackTrace();
		} finally {
			myData.closeConnection();
		}
		return result;

	}
}
