/*
*Generated by LiuRunze. 2009-06-09 18:02:15
*/
package com.genius.search.tablefield.actionbean;

public class InsertActionBean {
	
	private String id;
	
	private String fieldvalue;
	
	private String fieldtext;
	
	private String oftable;
	
	private String fieldtype;
	
	private String bz;

		
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}
	
	public String getFieldvalue() {
		return fieldvalue;
	}

	public void setFieldvalue(String fieldvalue) {
		this.fieldvalue = fieldvalue;
	}
	
	public String getFieldtext() {
		return fieldtext;
	}

	public void setFieldtext(String fieldtext) {
		this.fieldtext = fieldtext;
	}
	
	public String getOftable() {
		return oftable;
	}

	public void setOftable(String oftable) {
		this.oftable = oftable;
	}
	
	public String getFieldtype() {
		return fieldtype;
	}

	public void setFieldtype(String fieldtype) {
		this.fieldtype = fieldtype;
	}
	
	public String getBz() {
		return bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}


}
