/*
*Generated by LiuRunze. 2009-06-09 18:02:15
*/
package com.genius.search.tablefield.actionbean;

public class OftableActionBean {
	
	private String tabletext;
	
	private String tablevalue;

		
	public String getTabletext() {
		return tabletext;
	}

	public void setTabletext(String tabletext) {
		this.tabletext = tabletext;
	}
	
	public String getTablevalue() {
		return tablevalue;
	}

	public void setTablevalue(String tablevalue) {
		this.tablevalue = tablevalue;
	}


}
