/*
*Generated by GeniusPlatform. 2016-05-06 10:03:56
*/
package com.genius.BOSS.PCbar.action;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.jdom.Document;
import org.jdom.Element;
import org.jdom.output.Format;
import org.jdom.output.XMLOutputter;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.Controller;

import com.genius.BOSS.PCbar.IPCbar;
import com.genius.BOSS.PCbar.actionbean.*;

public final class InsertSelectEditAction implements Controller {
	public ModelAndView handleRequest(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
		HttpSession session = request.getSession();
		
		if (session.getAttribute("login") == null
				|| (!session.getAttribute("login").equals("true"))) {
			Element root = new Element("entity");
			
			Element actionState = new Element("actionState");
			Element fieldState = new Element("field");
			fieldState.setAttribute("name", "state");
			fieldState.setAttribute("value", "noSession");
			actionState.addContent(fieldState);

			root.addContent(actionState);
			Document doc = new Document(root);
			response.setContentType("application/xml;charset=GB2312");
			Format format = Format.getPrettyFormat();
			format.setEncoding("GB2312");
			XMLOutputter outer = new XMLOutputter(format);
			outer.output(doc, response.getWriter());

			return null;
		}
		
				String id = request.getParameter("id");

		
		ApplicationContext context = new ClassPathXmlApplicationContext(
				"applicationContext.xml");

		IPCbar PCbar = (IPCbar) context
				.getBean("PCbarProxy");
		PCbar.setSId(session.getAttribute("userId").toString());
		
		InsertActionBean bean = new InsertActionBean();
		bean = PCbar.insertSelectEdit(id);
		
		Element root = new Element("entity");
		Element row = new Element("row");
		
		
		Element field0 = new Element("field");
		field0.setAttribute("name", "id");
		field0.setAttribute("value", id);
		row.addContent(field0);
		
		Element field1 = new Element("field");
		field1.setAttribute("name", "resource_id");
		field1.setAttribute("value", bean.getResource_id()==null?"":bean.getResource_id());
		row.addContent(field1);
		
		Element field2 = new Element("field");
		field2.setAttribute("name", "img_url");
		field2.setAttribute("value", bean.getImg_url()==null?"":bean.getImg_url());
		row.addContent(field2);
		
		Element field3 = new Element("field");
		field3.setAttribute("name", "dest_type");
		field3.setAttribute("value", bean.getDest_type()==null?"":bean.getDest_type());
		row.addContent(field3);
		
		Element field4 = new Element("field");
		field4.setAttribute("name", "reource_param");
		field4.setAttribute("value", bean.getReource_param()==null?"":bean.getReource_param());
		row.addContent(field4);
		
		Element field5 = new Element("field");
		field5.setAttribute("name", "resource_order");
		field5.setAttribute("value", bean.getResource_order()==null?"":bean.getResource_order());
		row.addContent(field5);
		
		Element field6 = new Element("field");
		field6.setAttribute("name", "is_delete");
		field6.setAttribute("value", bean.getIs_delete()==null?"":bean.getIs_delete());
		row.addContent(field6);
		
		Element field7 = new Element("field");
		field7.setAttribute("name", "show_type");
		field7.setAttribute("value", bean.getShow_type()==null?"":bean.getShow_type());
		row.addContent(field7);
		
		Element field8 = new Element("field");
		field8.setAttribute("name", "resource_name");
		field8.setAttribute("value", bean.getResource_name()==null?"":bean.getResource_name());
		row.addContent(field8);
		
		Element field9 = new Element("field");
		field9.setAttribute("name", "show_position");
		field9.setAttribute("value", bean.getShow_position()==null?"":bean.getShow_position());
		row.addContent(field9);
		
		Element field10 = new Element("field");
		field10.setAttribute("name", "resource_type");
		field10.setAttribute("value", bean.getResource_type()==null?"":bean.getResource_type());
		row.addContent(field10);
		
		Element field11 = new Element("field");
		field11.setAttribute("name", "crreate_time");
		field11.setAttribute("value", bean.getCrreate_time()==null?"":bean.getCrreate_time());
		row.addContent(field11);
		
		Element field12 = new Element("field");
		field12.setAttribute("name", "create_user");
		field12.setAttribute("value", bean.getCreate_user()==null?"":bean.getCreate_user());
		row.addContent(field12);
		
		Element field13 = new Element("field");
		field13.setAttribute("name", "modify_time");
		field13.setAttribute("value", bean.getModify_time()==null?"":bean.getModify_time());
		row.addContent(field13);
		
		Element field14 = new Element("field");
		field14.setAttribute("name", "modify_user");
		field14.setAttribute("value", bean.getModify_user()==null?"":bean.getModify_user());
		row.addContent(field14);
		
		root.addContent(row);
		
		Element actionState = new Element("actionState");
		Element fieldState = new Element("field");
		fieldState.setAttribute("name", "state");
		fieldState.setAttribute("value", "session");
		actionState.addContent(fieldState);
		root.addContent(actionState);

		Document doc = new Document(root);
		response.setContentType("application/xml;charset=GB2312");
		Format format = Format.getPrettyFormat();
		format.setEncoding("GB2312");
		XMLOutputter outer = new XMLOutputter(format);
		outer.output(doc, response.getWriter());

		return null;
		
	}
}
