/*
*Generated by GeniusPlatform. 2016-04-11 15:57:15
*/
package com.genius.BOSS.cont_verify;

import java.util.*;

import org.genius.power.IPower;

import com.genius.BOSS.cont_verify.actionbean.*;;

public interface ICont_verify extends IPower {
	
	public int getTotalSize();	
	public int getTotalPageCount();
	public void setTotalSize(int totalSize);
	public String getSelectSql();
	public void setSelectSql(String selectSql);
	public ArrayList select(int pageNo, String orderField, String orderType, String searchField,String searchValue, String pager,String filter);
		
		
		
	public InsertActionBean insertSelectEdit(String id);	
	public boolean insertNew(String credit,String birthday,String area,String point,String name,String phone_no,String id_card_no,String role,String status,String account,String idcard_img,String sex,String email,String is_identify,String cert_img,String head_img,String register_time);public ArrayList areaInsertSelect();	
	public boolean insertEdit(String credit,String birthday,String area,String point,String name,String phone_no,String id_card_no,String role,String status,String account,String idcard_img,String sex,String email,String is_identify,String cert_img,String head_img,String register_time,String id);	
		
		
		
		
		
		
	public boolean delete(String[] id);	
		
		
	

}
