/*
*Generated by LiuRunze. 2009-06-09 18:02:15
*/
package com.genius.search.searchtype.action;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.genius.data.PageDataConfig;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.Controller;

import com.genius.adminmanager.login.Login;
import com.genius.search.searchtype.SearchtypeExt;
import com.genius.search.searchtype.actionbean.SelectActionBean;

public final class SelectAction implements Controller {
	public ModelAndView handleRequest(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
request.setCharacterEncoding("gbk");
response.setCharacterEncoding("gbk");
		HttpSession session = request.getSession();
		if (session.getAttribute("userName") == null
				|| !(Login.loginAdmin(session.getAttribute("userName")
						.toString(), session.getAttribute("roleId").toString()))) {
			return new ModelAndView("../error.jsp");
		}
		int pageNo;
		String asc = "false";
		String order = request.getParameter("order");
		String orderType = request.getParameter("ordertype");
		String searchField = request.getParameter("searchfield");
		String searchValue = request.getParameter("searchvalue");

		String url = request.getRequestURI() + "?";
		String query = request.getQueryString();
		if (query != null && !query.equals("null")) {
			url = request.getRequestURI() + "?" + query;
			if (query.indexOf("&order") > 0) {
				query = query.substring(0, query.indexOf("&order"));
			}
		} else {
			query = "";
		}

		if (url.indexOf("&order") > 0) {
			url = url.substring(0, url.indexOf("&order"));
		}

		if (orderType != null && !orderType.equals("null")) {
			if (orderType.equals("false")) {
				asc = "true";
			} else {
				asc = "false";
			}
		} else {
			orderType = "false";
		}

		if (request.getParameter("pageNo") != null) {
			pageNo = Integer.valueOf(request.getParameter("pageNo")).intValue();
			searchValue = new String(searchValue.getBytes("iso-8859-1"),"gb2312");
		} else {
			pageNo = 1;
		}

		List<SelectActionBean> myList = new ArrayList<SelectActionBean>();
		SearchtypeExt searchtypeExt = new SearchtypeExt();
		myList = searchtypeExt.select(pageNo, request.getParameter("order"), orderType, searchField, searchValue,null);
		PageDataConfig myData = new PageDataConfig(searchtypeExt.totalSize, 20, pageNo);
		String toolBar = myData
				.getToolbar(url + "&order=" + request.getParameter("order")
						+ "&ordertype=" + orderType + "&searchfield="
						+ searchField + "&searchvalue=" + searchValue);

		query = query + "&order=" + order + "&ordertype=" + orderType
				+ "&searchfield=" + searchField + "&searchvalue=" + searchValue
				+ "&pageNo=" + pageNo;

		request.setAttribute("toolBar", toolBar);
		request.setAttribute("url", url);
		request.setAttribute("query", query);
		request.setAttribute("ordertype", asc);
		request.setAttribute("dataList", myList);

		return new ModelAndView("st_index.jsp");
	}
}
	
