/*
*Generated by GeniusPlatform. 2016-05-06 10:03:56
*/
package com.genius.BOSS.hospital_m.action;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.jdom.Document;
import org.jdom.Element;
import org.jdom.output.Format;
import org.jdom.output.XMLOutputter;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.Controller;

import com.genius.BOSS.hospital_m.IHospital_m;
import com.genius.BOSS.hospital_m.actionbean.*;

public final class InsertSelectPrintAction implements Controller {
	public ModelAndView handleRequest(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
		HttpSession session = request.getSession();
		
		if (session.getAttribute("login") == null
				|| (!session.getAttribute("login").equals("true"))) {
			Element root = new Element("entity");
			
			Element actionState = new Element("actionState");
			Element fieldState = new Element("field");
			fieldState.setAttribute("name", "state");
			fieldState.setAttribute("value", "noSession");
			actionState.addContent(fieldState);

			root.addContent(actionState);
			Document doc = new Document(root);
			response.setContentType("application/xml;charset=GB2312");
			Format format = Format.getPrettyFormat();
			format.setEncoding("GB2312");
			XMLOutputter outer = new XMLOutputter(format);
			outer.output(doc, response.getWriter());

			return null;
		}
		
				String id = request.getParameter("id");

		
		ApplicationContext context = new ClassPathXmlApplicationContext(
				"applicationContext.xml");

		IHospital_m hospital_m = (IHospital_m) context
				.getBean("hospital_mProxy");
		hospital_m.setSId(session.getAttribute("userId").toString());
		
		InsertActionBean bean = new InsertActionBean();
		bean = hospital_m.insertSelectEdit(id);
		
		Element root = new Element("entity");
		Element row = new Element("row");
	
		
		Element field0 = new Element("field");
		field0.setAttribute("name", "id");
		field0.setAttribute("value", id);
		row.addContent(field0);
		
		Element field1 = new Element("field");
		field1.setAttribute("name", "name");
		field1.setAttribute("value", bean.getName()==null?"":bean.getName());
		row.addContent(field1);
		
		Element field2 = new Element("field");
		field2.setAttribute("name", "alias");
		field2.setAttribute("value", bean.getAlias()==null?"":bean.getAlias());
		row.addContent(field2);
		
		Element field3 = new Element("field");
		field3.setAttribute("name", "content");
		field3.setAttribute("value", bean.getContent()==null?"":bean.getContent());
		row.addContent(field3);
		
		Element field4 = new Element("field");
		field4.setAttribute("name", "address");
		field4.setAttribute("value", bean.getAddress()==null?"":bean.getAddress());
		row.addContent(field4);
		
		Element field5 = new Element("field");
		field5.setAttribute("name", "province");
		field5.setAttribute("value", bean.getProvince()==null?"":bean.getProvince());
		row.addContent(field5);
		
		Element field6 = new Element("field");
		field6.setAttribute("name", "city");
		field6.setAttribute("value", bean.getCity()==null?"":bean.getCity());
		row.addContent(field6);
		
		Element field7 = new Element("field");
		field7.setAttribute("name", "level");
		field7.setAttribute("value", bean.getLevel()==null?"":bean.getLevel());
		row.addContent(field7);
		
		Element field8 = new Element("field");
		field8.setAttribute("name", "phone");
		field8.setAttribute("value", bean.getPhone()==null?"":bean.getPhone());
		row.addContent(field8);
		
		root.addContent(row);
		
		Element actionState = new Element("actionState");
		Element fieldState = new Element("field");
		fieldState.setAttribute("name", "state");
		fieldState.setAttribute("value", "session");
		actionState.addContent(fieldState);
		root.addContent(actionState);

		Document doc = new Document(root);
		response.setContentType("application/xml;charset=GB2312");
		Format format = Format.getPrettyFormat();
		format.setEncoding("GB2312");
		XMLOutputter outer = new XMLOutputter(format);
		outer.output(doc, response.getWriter());

		return null;
		
	}
}
