/*
*Generated by GeniusPlatform. 2016-05-06 10:03:56
*/
package com.genius.BOSS.hospital_m.action;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.jdom.Document;
import org.jdom.Element;
import org.jdom.output.Format;
import org.jdom.output.XMLOutputter;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.Controller;

import org.genius.util.*;
import com.genius.BOSS.hospital_m.IHospital_m;

public final class InsertEditAction implements Controller {
	public ModelAndView handleRequest(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {

		HttpSession session = request.getSession();
		
		if (session.getAttribute("login") == null
				|| (!session.getAttribute("login").equals("true"))) {
			Element root = new Element("entity");
			
			Element actionState = new Element("actionState");
			Element fieldState = new Element("field");
			fieldState.setAttribute("name", "state");
			fieldState.setAttribute("value", "noSession");
			actionState.addContent(fieldState);

			root.addContent(actionState);
			Document doc = new Document(root);
			response.setContentType("application/xml;charset=GB2312");
			Format format = Format.getPrettyFormat();
			format.setEncoding("GB2312");
			XMLOutputter outer = new XMLOutputter(format);
			outer.output(doc, response.getWriter());

			return null;
		}
		
		String success = "true";

		String id = java.net.URLDecoder.decode(request.getParameter("id"),"UTF-8");
		String name = java.net.URLDecoder.decode(request.getParameter("name"),"UTF-8");
		String alias = java.net.URLDecoder.decode(request.getParameter("alias"),"UTF-8");
		String content = java.net.URLDecoder.decode(request.getParameter("content"),"UTF-8");
		String address = java.net.URLDecoder.decode(request.getParameter("address"),"UTF-8");
		String province = java.net.URLDecoder.decode(request.getParameter("province"),"UTF-8");
		String city = java.net.URLDecoder.decode(request.getParameter("city"),"UTF-8");
		String level = java.net.URLDecoder.decode(request.getParameter("level"),"UTF-8");
		String phone = java.net.URLDecoder.decode(request.getParameter("phone"),"UTF-8");


		ApplicationContext context = new ClassPathXmlApplicationContext(
				"applicationContext.xml");

		IHospital_m hospital_m = (IHospital_m) context
				.getBean("hospital_mProxy");
		hospital_m.setSId(session.getAttribute("userId").toString());
		try {
			if (hospital_m.insertEdit(province,city,content,name,id,phone,alias,level,address)) {
				success = "true";
			} else {
				success = "false";
			}
		} catch (NullPointerException e) {
			success = "noPower";
		}

		Element root = new Element("entity");
		Element row = new Element("row");
		Element field1 = new Element("field");
		field1.setAttribute("name", "success");
		field1.setAttribute("value", success);
		row.addContent(field1);

		root.addContent(row);
		
		Element actionState = new Element("actionState");
		Element fieldState = new Element("field");
		fieldState.setAttribute("name", "state");
		fieldState.setAttribute("value", "session");
		actionState.addContent(fieldState);
		root.addContent(actionState);

		Document doc = new Document(root);
		response.setContentType("application/xml;charset=GB2312");
		Format format = Format.getPrettyFormat();
		format.setEncoding("GB2312");
		XMLOutputter outer = new XMLOutputter(format);
		outer.output(doc, response.getWriter());

		return null;
	}
}

