/*
*Generated by GeniusPlatform. 2016-05-06 10:03:56
*/
package com.genius.BOSS.hospital_m.action;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.net.URLDecoder;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.genius.data.AdvancedSearchAnalysis;
import org.genius.data.PageDataConfig;
import org.genius.xml.ResponseXml;
import org.jdom.Document;
import org.jdom.Element;
import org.jdom.output.Format;
import org.jdom.output.XMLOutputter;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.Controller;

import com.genius.BOSS.hospital_m.IHospital_m;
import com.genius.BOSS.hospital_m.actionbean.*;

public final class SelectAction implements Controller {
	public ModelAndView handleRequest(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {

		HttpSession session = request.getSession();
		
		if (session.getAttribute("login") == null
				|| (!session.getAttribute("login").equals("true"))) {
			Element root = new Element("entity");
			
			Element actionState = new Element("actionState");
			Element fieldState = new Element("field");
			fieldState.setAttribute("name", "state");
			fieldState.setAttribute("value", "noSession");
			actionState.addContent(fieldState);

			root.addContent(actionState);
			Document doc = new Document(root);
			response.setContentType("application/xml;charset=GB2312");
			Format format = Format.getPrettyFormat();
			format.setEncoding("GB2312");
			XMLOutputter outer = new XMLOutputter(format);
			outer.output(doc, response.getWriter());

			return null;
		}
		
		String requestUrl = "";
		
		

		int pageNo;
		String orderType = request.getParameter("ordertype");
		String searchField = request.getParameter("searchfield");
		String searchValue = request.getParameter("searchvalue");
		String searchValuePage = request.getParameter("searchvalue");
		String pager = request.getParameter("pager");
		searchValue=AdvancedSearchAnalysis.adAnalysis(searchField,searchValue);
		
		if(!(searchValuePage==null||searchValuePage.length()<=0)){
			searchValuePage = URLDecoder.decode(searchValuePage,"UTF-8");
		}

		String url = request.getRequestURI() + "?";
		String query = request.getQueryString();
		if (query != null && !query.equals("null")) {
			url = request.getRequestURI() + "?" + query;
		} 

		if (url.indexOf("&order") > 0) {
			url = url.substring(0, url.indexOf("&order"));
		}

		if (orderType == null || orderType.equals("null")) {
			orderType = "true";
		}

		if (request.getParameter("pageNo") != null) {
			pageNo = Integer.valueOf(request.getParameter("pageNo")).intValue();
		} else {
			pageNo = 1;
		}

		ArrayList myList = new ArrayList();
		
		ApplicationContext context = new ClassPathXmlApplicationContext(
				"applicationContext.xml");

		IHospital_m hospital_m = (IHospital_m) context
				.getBean("hospital_mProxy");
				
		hospital_m.setSId(session.getAttribute("userId").toString());

		try {
		
			myList = hospital_m.select(pageNo, request.getParameter("order"), orderType, searchField, searchValue, pager,null);
		
		} catch (NullPointerException e) {
			
			ResponseXml responseXml = new ResponseXml();
			Document doc = responseXml.actionStateResponse("NullPointerException");
			response.setContentType("application/xml;charset=GB2312");
			Format format = Format.getPrettyFormat();
			format.setEncoding("GB2312");
			XMLOutputter outer = new XMLOutputter(format);
			outer.output(doc, response.getWriter());

			return null;
		}
		
		if (myList == null) {
			String[] fields={"id","name","alias","address","level","phone"};
			ResponseXml responseXml=new ResponseXml();
			Document doc = responseXml.noPowerResponse(fields);
			response.setContentType("application/xml;charset=GB2312");
			Format format = Format.getPrettyFormat();
			format.setEncoding("GB2312");
			XMLOutputter outer = new XMLOutputter(format);
			outer.output(doc, response.getWriter());

			return null;
		}
		
		PageDataConfig myData = new PageDataConfig(hospital_m.getTotalSize(),50,
				pageNo);
		String toolBar = myData
				.getImagePageBar(url + requestUrl + "&order="
						+ request.getParameter("order") + "&ordertype="
						+ orderType + "&searchfield=" + searchField
						+ "&searchvalue=" + searchValuePage);
		boolean isOverMax = false;
		if(hospital_m.getTotalPageCount()>1)
			isOverMax = true;
			
		Element root = new Element("entity");
		Iterator it = myList.iterator();

		while (it.hasNext()) {
			SelectActionBean bean = (SelectActionBean) it.next();
			Element row = new Element("row");
			
			Element field0 = new Element("field");
			field0.setAttribute("name", "id");
			field0.setAttribute("value", bean.getId()==null?"":bean.getId());
			row.addContent(field0);
			
			Element field1 = new Element("field");
			field1.setAttribute("name", "name");
			field1.setAttribute("value", bean.getName()==null?"":bean.getName());
			row.addContent(field1);
			
			Element field2 = new Element("field");
			field2.setAttribute("name", "alias");
			field2.setAttribute("value", bean.getAlias()==null?"":bean.getAlias());
			row.addContent(field2);
			
			Element field3 = new Element("field");
			field3.setAttribute("name", "address");
			field3.setAttribute("value", bean.getAddress()==null?"":bean.getAddress());
			row.addContent(field3);
			
			Element field4 = new Element("field");
			field4.setAttribute("name", "level");
			field4.setAttribute("value", bean.getLevel()==null?"":bean.getLevel());
			row.addContent(field4);
			
			Element field5 = new Element("field");
			field5.setAttribute("name", "phone");
			field5.setAttribute("value", bean.getPhone()==null?"":bean.getPhone());
			row.addContent(field5);
			
			root.addContent(row);
			bean = null;
		}
		
		Element pageBar = new Element("pageBar");
		Element fieldPage = new Element("field");
		fieldPage.setAttribute("name", "page");
		fieldPage.setAttribute("totalPageCount",String.valueOf(isOverMax));
		fieldPage.setAttribute("value", toolBar);
		pageBar.addContent(fieldPage);
		Element fieldUrl = new Element("field");
		fieldUrl.setAttribute("name", "url");
		fieldUrl.setAttribute("value", url);
		pageBar.addContent(fieldUrl);
		root.addContent(pageBar);
		
		Element actionState = new Element("actionState");
		Element fieldState = new Element("field");
		fieldState.setAttribute("name", "state");
		fieldState.setAttribute("value", "session");
		actionState.addContent(fieldState);
		root.addContent(actionState);
		
		Document doc = new Document(root);
		response.setContentType("application/xml;charset=GB2312");
		Format format = Format.getPrettyFormat();
		format.setEncoding("GB2312");
		XMLOutputter outer = new XMLOutputter(format);
		outer.output(doc, response.getWriter());

		return null;
	}
}
	
