/*
*Generated by GeniusPlatform. 2016-04-11 15:57:15
*/
package com.genius.BOSS.ordinary;

import java.sql.ResultSet;
import java.sql.SQLException;
import org.genius.data.DataConfig;
import com.genius.BOSS.ordinary.actionbean.*;

public class OrdinaryExt extends Ordinary{

    public SelectActionBean getWindowData(String id) {
    	SelectActionBean bean = new SelectActionBean();
		DataConfig myData = new DataConfig();
		try {
			myData.openConnection();
			String sql = "select * from table where id="+id;
			ResultSet rs = myData.executeQuery(sql);
			while (rs.next()) {
				/*
				bean.setName(rs.getString("name"));
				*/
			}
		} catch (SQLException e) {
			e.printStackTrace();
		} finally {
			myData.closeConnection();
		}

		return bean;
    }
}


