/*
*Generated by GeniusPlatform. 2016-04-11 15:57:14
*/
package com.genius.BOSS.verify;

import java.util.*;

import org.genius.power.IPower;

import com.genius.BOSS.verify.actionbean.*;;

public interface IVerify extends IPower {
	
	public int getTotalSize();	
	public int getTotalPageCount();
	public void setTotalSize(int totalSize);
	public String getSelectSql();
	public void setSelectSql(String selectSql);
	public ArrayList select(int pageNo, String orderField, String orderType, String searchField,String searchValue, String pager,String filter);
		
		
		
	public InsertActionBean insertSelectEdit(String id);	
	public boolean insertNew(String department,String birthday,String point,String section,String id_card_no,String role,String account,String idcard_img,String job_title,String cert_img,String college,String hospital,String liaisons,String credit,String area,String name,String phone_no,String brief,String status,String sex,String modify_time,String is_identify,String head_img,String register_time,String society);public ArrayList hospitalInsertSelect();public ArrayList departmentInsertSelect();public ArrayList job_titleInsertSelect();public ArrayList sectionInsertSelect();public ArrayList liaisonsInsertSelect();public ArrayList areaInsertSelect();	
	public boolean insertEdit(String department,String birthday,String point,String section,String id_card_no,String role,String account,String idcard_img,String job_title,String cert_img,String college,String id,String hospital,String liaisons,String credit,String area,String name,String phone_no,String brief,String status,String sex,String modify_time,String is_identify,String head_img,String register_time,String society);	
		
		
		
		
		
		
	public boolean delete(String[] id);	
		
		
	

}
